"""empty message

Revision ID: 73cc56f908ce
Revises: 18b25f3ecde3
Create Date: 2025-09-21 14:27:11.179557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cc56f908ce'
down_revision = '18b25f3ecde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_role_menu',
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['rid'], ['t_role.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_role_menu')
    # ### end Alembic commands ###
