"""empty message

Revision ID: 8da13080e202
Revises: 31c5d00862b5
Create Date: 2025-09-26 20:50:33.013192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da13080e202'
down_revision = '31c5d00862b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_picture', sa.Column('path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_picture', 'path')
    # ### end Alembic commands ###
