"""empty message

Revision ID: aab9fe975b72
Revises: 7400ad6ff150
Create Date: 2025-09-21 11:02:07.782661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab9fe975b72'
down_revision = '7400ad6ff150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('rid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_user', 't_role', ['rid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user', type_='foreignkey')
    op.drop_column('t_user', 'rid')
    # ### end Alembic commands ###
