"""empty message

Revision ID: b79bd0985ca8
Revises: 1514460816eb
Create Date: 2025-09-16 14:37:22.061825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79bd0985ca8'
down_revision = '1514460816eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('t_user', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'update_time')
    op.drop_column('t_user', 'create_time')
    # ### end Alembic commands ###
